### ISSUE TITLE
Upgrade to @graphprotocol/graph-ts 0.26.0

### ISSUE THREAD

**Issue by 0xJurassicPunk** [LimeChain/matchstick-as#50]
Hello,
is there any plan to bump the dependencies to the latest version of graph-ts?
https://www.npmjs.com/package/@graphprotocol/graph-ts

**Comment by franz101** [comment]
Receipts are also new in ^0.27

**Comment by dimitrovmaksim** [comment]
Bumped graph-ts version to 0.26.0 in matchstick-as 0.4.3. graph-ts 0.27.0 is still in alpha

**Comment by dimitrovmaksim** [comment]
matchstick 0.4.4 is released, bumped graph-ts to 0.27.0. newMockEvent will now also create a mock TransactionReceipt and Log
